name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.x', 'stable']
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Initialize Go module if needed
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/gliptak/httpmock
          go mod tidy
        fi
    
    - name: Run tests
      run: go test -v ./